[pytest]
addopts = --alluredir=allure-results 
pythonpath = .
markers =
    login: mark test as part of login tests
    positive: mark test as part of positive tests
    negative: mark test as part of negative tests
    select_sort: mark test as part of select sort tests
    cart: mark test as part of cart tests
    add_to_cart: mark test as part of add to cart tests
    remove_from_cart: mark test as part of remove from cart tests
    edge_cases: mark test as part of edge cases tests
    smoke: mark test as part of smoke tests

[allure]
results_dir = allure-results