[pytest]
addopts = --alluredir=allure-results 
pythonpath = .
markers =
    login: mark test as part of login tests
    positive: mark test as part of positive tests
    negative: mark test as part of negative tests
    scroll: mark test as part of scroll tests
    hover: mark test as part of hover tests

[allure]
results_dir = allure-results